version: '3.4'

services:

  conductor-server:
    environment:
      - CONFIG_PROP=config-mysql-grpc.properties
    image: conductor:server
    build:
      context: ../../
      dockerfile: docker/server/Dockerfile
    ports:
      - 8080:8080
      - 8090:8090
    networks:
      - internal
    depends_on:
      - mysql
      - elasticsearch

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../../
      dockerfile: docker/ui/Dockerfile
    ports:
      - 5000:5000
    networks:
      - internal
    depends_on:
      - conductor-server
